---
name: Build buildah runner
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: self-hosted
    env:
      CONTEXT: "."
      DOCKER_FILE: "buildah-runner-dockerfile"
      REGISTRY: "ghcr.io"
      REPO_NAME: "${{ github.repository }}"
      USER: "${{ github.repository_owner }}"
      IMAGE_NAME: "buildah-runner"
      IMAGE_TAG: "latest"
    steps:
      - uses: actions/checkout@master        
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ secrets.TOKEN }}
          image: ${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}}
          tag: ${{ env.IMAGE_TAG }}
          cache: true
          cache_registry: cache
