---
name: Build buildah runner
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: ubuntu-latest
    env:
      DOCKER_FILE: "buildah-runner-dockerfile"
      REGISTRY: "ghcr.io"
      USER: "daeuniverse"
      IMAGE_NAME: "buildah-runner"
    steps:
      - uses: actions/checkout@master        
      - name: Get HEAD git sha
        id: export_commit_sha
        run: |
          echo "::set-output name=sha_long::${{ github.sha }}"
          echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c1-6)"
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ secrets.TOKEN }}
          image: ${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ steps.export_commit_sha.outputs.sha_short }}
          cache: true
          cache_registry: cache

      - name: Echo image uri
        run: |
          echo "ImageURI: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.export_commit_sha.outputs.sha_short }}"
