---
name: Build buildah runner
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: self-hosted
    env:
      MANIFEST_NAME: "buildah-runner"
      CONTEXT: "."
      DOCKER_FILE: "buildah-runner-dockerfile"
      REGISTRY: "ghcr.io"
      REPO_NAME: "${{ github.repository }}"
      USER: "${{ github.repository_owner }}"
      IMAGE_NAME: "buildah-runner"
      IMAGE_TAG: "v0.1.1"
    steps:
      - uses: actions/checkout@master        
      - name: Install Buildah
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install buildah -y
          sudo cat << EOF | sudo tee -a /etc/containers/registries.conf
          unqualified-search-registries=["docker.io"]
          EOF
          
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          context: .
          containerfiles: ${{ env.DOCKER_FILE }}

      - name: Push to registry
        shell: bash
        run: |          
          buildah push \
            --creds=$USER:${{ secrets.TOKEN }} \
            ${MANIFEST_NAME} \
            "docker://${REGISTRY}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}"
            
          buildah push \
            --creds=$USER:${{ secrets.TOKEN }} \
            ${MANIFEST_NAME} \
            "docker://${REGISTRY}/${REPO_NAME}/${IMAGE_NAME}:latest"
