---
name: Build buildah-runner
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: ubuntu-latest
    env:
      DOCKER_FILE: "buildah-runner-dockerfile"
      USER: "daeuniverse"
      IMAGE_NAME: "buildah-runner"
    steps:
      - uses: actions/checkout@master
      - name: Get HEAD git sha
        id: export_commit_sha
        run: |
          echo "sha_long=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔨 ${{ github.actor }} pushed a new commit: ${{ steps.export_commit_sha.outputs.sha_short }}
            
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: [${{ github.repository }}](https://github.com/daeuniverse/container-estate)
            
            Build: [${{ github.run_number }}](https://github.com/daeuniverse/container-estate/actions/run/${{ github.run_id }})
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ env.USER }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ env.USER }}/${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ steps.export_commit_sha.outputs.sha_short }}
          cache: true
          cache_registry: quay.io/${{ env.USER }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-${{ env.SHORT_SHA }}-${{ github.run_number }}"
