---
name: Build buildah-runner
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/buildah-runner-build.yml
      - buildah-runner-dockerfile

jobs:
  # Pre-Action Stage
  pre-build:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-start.yml@master
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      
  # Build Stage
  build-runner:
    runs-on: ubuntu-latest
    needs: [pre-build]
    env:
      DOCKER_FILE: "buildah-runner-dockerfile"
      USER: "daeuniverse"
      IMAGE_NAME: "buildah-runner"
    outputs:
      USER: ${{ env.USER }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ env.USER }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ env.USER }}/${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ needs.pre-build.outputs.git_sha_short }}-${{ github.run_number }}
          cache: true
          cache_registry: quay.io/${{ env.USER }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ needs.pre-build.outputs.git_sha_short }}-${{ github.run_number }}"
          
      - name: Pass envs to next stage
        run: |
          echo "USER=$USER" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          
  # Post-Action Stage
  post-build:
    needs: [pre-build,build-runner]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-result.yml@master
    with:
      USER: ${{ needs.build-runner.outputs.USER }}
      IMAGE_NAME: ${{ needs.build-runner.outputs.IMAGE_NAME }}
      SHA_SHORT: ${{ needs.pre-build.outputs.git_sha_short }}
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
