---
name: Build buildah-runner
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/buildah-runner-build.yml
      - buildah-runner-dockerfile

env:
  DOCKER_FILE: "buildah-runner-dockerfile"
  USER: "daeuniverse"
  IMAGE_NAME: "buildah-runner"

jobs:
  # Pre-Action Stage
  pre-build:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-start.yml@master
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      
  # Build Stage
  build-runner:
    runs-on: ubuntu-latest
    needs: [pre-build]
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ env.USER }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ env.USER }}/${{ env.IMAGE_NAME }}
          build_file: ${{ env.DOCKER_FILE }}
          tag: ${{ needs.pre-build.outputs.git_sha_short }}-${{ github.run_number }}
          cache: true
          cache_registry: quay.io/${{ env.USER }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ needs.pre-build.outputs.git_sha_short }}-${{ github.run_number }}"
          
  # Post-Action Stage
  post-build:
    needs: [pre-build,build-runner]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/notify-build-result.yml@master
    with:
      USER: ${{ env.USER }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      SHA_SHORT: ${{ needs.pre-build.outputs.git_sha_short }}
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#   post-build:
#     runs-on: ubuntu-latest
#     needs: [pre-build,build-runner]
#     steps:     
#       - name: Send telegram message on push
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: markdown
#           message: |
#             🏗 ${{ github.repository }}: Build #${{ github.run_number }} succeeded!
            
#             📦 Image URI: quay.io/${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ needs.pre-build.outputs.git_sha_short }}-${{ github.run_number }}
            
#             🔨 Build Detail: [#${{ github.run_number }}](https://github.com/daeuniverse/container-estate/actions/runs/${{ github.run_id }})
