---
name: Kaniko build for self-runner-daed
on:
  workflow_dispatch:
jobs:
  build-runner:
#     runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.TOKEN }}
          image: self-runner-daed
          build_file: self-runner-daed-dockerfile
          tag: latest
          cache: true
          cache_registry: cache
