---
name: Buildah multi-arch build for self-runner-daed
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Install Buildah
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install buildah -y
          sudo cat << EOF | sudo tee -a /etc/containers/registries.conf
          unqualified-search-registries=["docker.io"]
          EOF
          
      - name: Build multi-arch images
        uses: redhat-actions/buildah-build@v2
        id: build-iamge
        with:
          image: self-runner-daed
          tags: v1 ${{ github.sha }}
          context: .
          containerfiles: self-runner-daed-dockerfile
          platforms: linux/amd64,linux/arm64
          
      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/daeuniverse
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
            
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"

