---
name: Buildah multi-arch build for self-runner-daed
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: self-hosted
    env:
      MANIFEST_NAME: "multiarch-build"
      CONTEXT: "."
      REGISTRY: "ghcr.io"
      USER: "daeuniverse"
      IMAGE_NAME: "self-runner-daed"
      IMAGE_TAG: "v0.1.1"
    steps:
      - uses: actions/checkout@master        
      - name: Install Buildah
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install buildah -y
          sudo cat << EOF | sudo tee -a /etc/containers/registries.conf
          unqualified-search-registries=["docker.io"]
          EOF
          
      - name: Create multi-architecture manifest
        shell: bash
        run: |
          buildah manifest create ${MANIFEST_NAME}
          
      - name: Build multi-arch image
        shell: bash
        run: |
          buildah bud \
            --tag "${REGISTRY}/${USER}/${IMAGE_NAME}:${IMAGE_TAG}" \
            --manifest ${MANIFEST_NAME} \
            --file self-runner-daed-dockerfile \
            --arch amd64 \
            ${CONTEXT}
            
          buildah bud \
            --tag "${REGISTRY}/${USER}/${IMAGE_NAME}:${IMAGE_TAG}" \
            --manifest ${MANIFEST_NAME} \
            --file self-runner-daed-dockerfile \
            --arch arm64 \
            ${CONTEXT}
            
#       - name: Push to registry
#         shell: bash
#         run: |
#           buildah manifest push --all \
#             ${MANIFEST_NAME} \
#             "docker://${REGISTRY}/${USER}/${IMAGE_NAME}:${IMAGE_TAG}"


