---
name: Buildah multi-arch build for self-runner-daed
on:
  workflow_dispatch:
jobs:
  build-runner:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Install Buildah
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install buildah -y
          sudo cat << EOF | sudo tee -a /etc/containers/registries.conf
          unqualified-search-registries=["docker.io"]
          EOF
      - name: build multi-arch images
        uses: redhat-actions/buildah-build@v2
        with:
          image: self-runner-daed
          tags: v1 ${{ github.sha }}
          context: .
          containerfiles: self-runner-daed-dockerfile
          platforms: linux/amd64,linux/arm64
